[0.035s] Invoking command in '/home/max/ros2_ws/build/tutorial_interfaces': /usr/bin/cmake --build /home/max/ros2_ws/build/tutorial_interfaces -- -j2 -l2
[0.068s] -- Found geometry_msgs: 4.2.2 (/opt/ros/humble/share/geometry_msgs/cmake)
[0.386s] -- Found rosidl_generator_c: 3.1.3 (/opt/ros/humble/share/rosidl_generator_c/cmake)
[0.392s] -- Found rosidl_adapter: 3.1.3 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.399s] -- Found rosidl_generator_cpp: 3.1.3 (/opt/ros/humble/share/rosidl_generator_cpp/cmake)
[0.434s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.459s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.660s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.913s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.913s]   execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
[0.913s]   tutorial_interfaces --arguments-file
[0.914s]   /home/max/ros2_ws/build/tutorial_interfaces/rosidl_adapter__arguments__tutorial_interfaces.json
[0.914s]   --output-dir
[0.914s]   /home/max/ros2_ws/build/tutorial_interfaces/rosidl_adapter/tutorial_interfaces
[0.914s]   --output-file
[0.914s]   /home/max/ros2_ws/build/tutorial_interfaces/rosidl_adapter/tutorial_interfaces.idls)
[0.914s]   returned error code 1:
[0.914s] 
[0.914s]   Error processing 'using std::placeholders::_1;' of
[0.914s]   'tutorial_interfaces/Num': ''using' is an invalid message name.  It should
[0.914s]   have the pattern '^[A-Z][A-Za-z0-9]*$''
[0.914s] 
[0.914s]   Traceback (most recent call last):
[0.915s] 
[0.915s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.915s]       return _run_code(code, main_globals, None,
[0.915s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.915s]       exec(code, run_globals)
[0.915s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.915s]       sys.exit(main())
[0.915s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.915s]       abs_idl_file = convert_to_idl(
[0.915s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[0.915s]       return convert_msg_to_idl(
[0.915s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[0.916s]       msg = parse_message_string(package_name, input_file.stem, content)
[0.916s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 520, in parse_message_string
[0.916s]       Type(type_string, context_package_name=pkg_name),
[0.916s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 277, in __init__
[0.916s]       super(Type, self).__init__(
[0.916s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[0.916s]       raise InvalidResourceName(
[0.916s] 
[0.916s]   rosidl_adapter.parser.InvalidResourceName: 'using' is an invalid message
[0.916s]   name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[0.916s] 
[0.916s] Call Stack (most recent call first):
[0.916s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.916s]   CMakeLists.txt:11 (rosidl_generate_interfaces)
[0.917s] 
[0.917s] [0m
[0.917s] -- Configuring incomplete, errors occurred!
[0.917s] See also "/home/max/ros2_ws/build/tutorial_interfaces/CMakeFiles/CMakeOutput.log".
[0.921s] gmake: *** [Makefile:1179: cmake_check_build_system] Error 1
[0.924s] Invoked command in '/home/max/ros2_ws/build/tutorial_interfaces' returned '2': /usr/bin/cmake --build /home/max/ros2_ws/build/tutorial_interfaces -- -j2 -l2
